# Generated by Django 5.1.1 on 2024-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('option1', 'FÁBÓL KÉSZÜLT'), ('option2', 'KÖTÖTT-HORGOLT'), ('option3', 'PÖTTYÖSCICA'), ('option4', 'TEXTIL')], default='option1', max_length=10),
        ),
    ]
