# Generated by Django 5.1.1 on 2024-10-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddres',
            new_name='ShippingAddress',
        ),
    ]
