# Generated by Django 5.1.1 on 2024-10-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
