# Generated by Django 5.1.1 on 2024-10-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='street_number',
        ),
    ]
