# Generated by Django 5.1.1 on 2024-10-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_state_shippingaddress_street_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Vásárló', 'verbose_name_plural': 'Vásárlók'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Rendelés', 'verbose_name_plural': 'Rendelések'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Rendelési tétel', 'verbose_name_plural': 'Rendelési tételek'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Termék', 'verbose_name_plural': 'Termékek'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Szállítási cím', 'verbose_name_plural': 'Szállítási címek'},
        ),
    ]
