# Generated by Django 5.1.1 on 2024-10-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_user_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
