# Generated by Django 5.1.1 on 2024-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
