# Generated by Django 5.1.1 on 2024-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBarText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Cím')),
                ('content', models.TextField(verbose_name='Szöveg')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó frissítés')),
            ],
        ),
    ]
