# Generated by Django 5.1.1 on 2024-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_topbartext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Szállítási díj (Ft)')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingyenes szállítás küszöb (Ft)')),
            ],
        ),
    ]
