# Generated by Django 5.1.1 on 2024-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_shippingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=500),
        ),
    ]
